from cafeteria import *

print("===== SISTEMA CAFETERÍA =====")
print()

cliente1 = Cliente(1, "Isaac", "isaac@mail.com")
cliente2 = Cliente(2, "Ana", "ana@mail.com")
cliente3 = Cliente(3, "Mario", "mario@mail.com")
cliente4 = Cliente(4, "Lucia", "lucia@mail.com")
cliente5 = Cliente(5, "Pedro", "pedro@mail.com")
cliente6 = Cliente(6, "Sofia", "sofia@mail.com")
cliente7 = Cliente(7, "Diego", "diego@mail.com")
cliente8 = Cliente(8, "Valeria", "valeria@mail.com")
cliente9 = Cliente(9, "Andres", "andres@mail.com")
cliente10 = Cliente(10, "Fernanda", "fernanda@mail.com")

empleado1 = Empleado(11, "Carlos", "carlos@mail.com", "E01", "BARISTA")
empleado2 = Empleado(12, "Luis", "luis@mail.com", "E02", "GERENTE")
empleado3 = Empleado(13, "Raul", "raul@mail.com", "E03", "BARISTA")
empleado4 = Empleado(14, "Elena", "elena@mail.com", "E04", "BARISTA")
empleado5 = Empleado(15, "Jorge", "jorge@mail.com", "E05", "CAJA")
empleado6 = Empleado(16, "Paty", "paty@mail.com", "E06", "BARISTA")
empleado7 = Empleado(17, "Hugo", "hugo@mail.com", "E07", "CAJA")
empleado8 = Empleado(18, "Carmen", "carmen@mail.com", "E08", "BARISTA")
empleado9 = Empleado(19, "Ivan", "ivan@mail.com", "E09", "GERENTE")
empleado10 = Empleado(20, "Laura", "laura@mail.com", "E10", "CAJA")

cliente1.login()
cliente2.login()
cliente3.login()
cliente4.login()
cliente5.login()
cliente6.login()
cliente7.login()
cliente8.login()
cliente9.login()
cliente10.login()
empleado1.login()
empleado2.login()
empleado3.login()
empleado4.login()
empleado5.login()
empleado6.login()
empleado7.login()
empleado8.login()
empleado9.login()
empleado10.login()
print()

cafe1 = Bebida(1, "Café", 50, "Grande", "CALIENTE")
cafe1.agregarExtra("Leche de almendra", 10)
cafe1.agregarExtra("Extra shot", 15)
frappe2 = Bebida(2, "Frappe", 60, "Mediano", "FRIA")
frappe2.agregarExtra("Crema batida", 12)
bebida3 = Bebida(3, "Capuccino", 55, "Mediano", "CALIENTE")
bebida4 = Bebida(4, "Latte", 58, "Grande", "CALIENTE")
bebida5 = Bebida(5, "Chocolate caliente", 52, "Grande", "CALIENTE")
bebida6 = Bebida(6, "Té", 40, "Mediano", "CALIENTE")
bebida7 = Bebida(7, "Matcha", 65, "Mediano", "FRIA")
bebida8 = Bebida(8, "Americano", 45, "Grande", "CALIENTE")
bebida9 = Bebida(9, "Mocha", 62, "Grande", "CALIENTE")
bebida10 = Bebida(10, "Cold Brew", 70, "Grande", "FRIA")

pastel = Postre(11, "Pastel chocolate", 45, False, False)
galleta = Postre(12, "Galleta", 25, True, True)
brownie = Postre(13, "Brownie", 35, False, False)
cheesecake = Postre(14, "Cheesecake", 50, False, False)
cupcake = Postre(15, "Cupcake", 30, False, False)
panque = Postre(16, "Panqué", 28, True, False)
dona = Postre(17, "Donut", 26, True, False)
croissant = Postre(18, "Croissant", 33, False, False)
pay_limon = Postre(19, "Pay de limón", 48, False, False)
muffin = Postre(20, "Muffin", 29, True, False)

print("Productos creados:")
print(cafe1)
print(frappe2)
print(pastel)
print(galleta)
print(brownie)
print(cheesecake)
print(cupcake)
print(panque)
print(dona)
print(croissant)
print(pay_limon)
print(muffin)
print()

pedido1 = Pedido([cafe1, pastel])
pedido2 = Pedido([frappe2, galleta])
pedido3 = Pedido([cafe1, frappe2, pastel])
pedido4 = Pedido([bebida3, brownie])
pedido5 = Pedido([bebida4, cheesecake])
pedido6 = Pedido([bebida5, cupcake])
pedido7 = Pedido([bebida6, panque])
pedido8 = Pedido([bebida7, dona])
pedido9 = Pedido([bebida8, croissant])
pedido10 = Pedido([bebida9, pay_limon])

print("Calculando totales...")
pedido1.calcularTotal()
pedido2.calcularTotal()
pedido3.calcularTotal()
pedido4.calcularTotal()
pedido5.calcularTotal()
pedido6.calcularTotal()
pedido7.calcularTotal()
pedido8.calcularTotal()
pedido9.calcularTotal()
pedido10.calcularTotal()
print()

cliente1.realizarPedido(pedido1)
cliente1.realizarPedido(pedido2)
cliente2.realizarPedido(pedido3)
cliente4.realizarPedido(pedido5)
cliente5.realizarPedido(pedido6)
cliente6.realizarPedido(pedido7)
cliente7.realizarPedido(pedido8)
cliente8.realizarPedido(pedido9)
cliente9.realizarPedido(pedido10)
print()

print("Historial de Isaac:")
cliente1.consultarHistorial()
print()

print("Historial de Ana:")
cliente2.consultarHistorial()

print("Historial de Mario:")
cliente3.consultarHistorial()

print("Historial de Lucia:")
cliente4.consultarHistorial()

print("Historial de Pedro:")
cliente5.consultarHistorial()

empleado1.cambiarEstadoPedido(pedido1, "PREPARANDO")
empleado1.cambiarEstadoPedido(pedido2, "PREPARANDO")

empleado2.cambiarEstadoPedido(pedido1, "ENTREGADO")
empleado2.cambiarEstadoPedido(pedido2, "ENTREGADO")
print()

inventario = Inventario()
inventario.ingredientes["Cafe"] = 20
inventario.ingredientes["Leche"] = 15
inventario.ingredientes["Chocolate"] = 10

print("Inventario inicial:")
print(inventario.ingredientes)
print()

inventario.reducirStock("Cafe", 5)
inventario.reducirStock("Leche", 3)
inventario.reducirStock("Chocolate", 2)
inventario.reducirStock("Azucar", 1)
print()

print("Inventario actual:")
print(inventario.ingredientes)
print()

print("Combinando pedidos...")
pedido_total = pedido1 + pedido2
pedido_total.calcularTotal()
print()

print("Multiplicando pedido...")
pedido_x3 = pedido2 * 3
pedido_x3.calcularTotal()
print()

print("¿pedido1 == pedido2?")
print(pedido1 == pedido2)

print("¿cliente1 == cliente2?")
print(cliente1 == cliente2)
print()

cliente1.puntosFidelidad = 100
cliente1.canjearPuntos(50)
cliente1.canjearPuntos(100)
print()

print("Total de personas creadas:", Persona.total_personas)
print("Total de pedidos creados:", Pedido.total_pedidos)
