from cine import*

usuario1 = Usuario(1, "Isaac", "isaac@mail.com", "222")
usuario2 = Usuario(2, "Ana", "ana@mail.com", "333")
usuario3 = Usuario(3, "Mario", "mario@mail.com", "555")
usuario4 = Usuario(4, "Lucia", "lucia@mail.com", "666")
usuario5 = Usuario(5, "Pedro", "pedro@mail.com", "777")
usuario6 = Usuario(6, "Sofia", "sofia@mail.com", "888")
usuario7 = Usuario(7, "Diego", "diego@mail.com", "999")
usuario8 = Usuario(8, "Valeria", "valeria@mail.com", "1010")
usuario9 = Usuario(9, "Andres", "andres@mail.com", "1111")
usuario10 = Usuario(10, "Fernanda", "fernanda@mail.com", "1212")

print(usuario1.login())
print(usuario2.login())
print(usuario3.login())
print(usuario4.login())
print(usuario5.login())
print(usuario6.login())
print(usuario7.login())
print(usuario8.login())
print(usuario9.login())
print(usuario10.login())

empleado1 = Empleado(11, "Carlos", "carlos@mail.com", "111", "E01", "ADMIN", "Matutino")
empleado2 = Empleado(12, "Luis", "luis@mail.com", "444", "E02", "TAQUILLERO", "Vespertino")
empleado3 = Empleado(13, "Raul", "raul@mail.com", "1313", "E03", "TAQUILLERO", "Mixto")
empleado4 = Empleado(14, "Elena", "elena@mail.com", "1414", "E04", "ADMIN", "Matutino")
empleado5 = Empleado(15, "Jorge", "jorge@mail.com", "1515", "E05", "TAQUILLERO", "Vespertino")
empleado6 = Empleado(16, "Paty", "paty@mail.com", "1616", "E06", "ADMIN", "Mixto")
empleado7 = Empleado(17, "Hugo", "hugo@mail.com", "1717", "E07", "TAQUILLERO", "Matutino")
empleado8 = Empleado(18, "Carmen", "carmen@mail.com", "1818", "E08", "ADMIN", "Vespertino")
empleado9 = Empleado(19, "Ivan", "ivan@mail.com", "1919", "E09", "TAQUILLERO", "Mixto")
empleado10 = Empleado(20, "Laura", "laura@mail.com", "2020", "E10", "ADMIN", "Matutino")

print(empleado1.login())
print(empleado2.login())
print(empleado3.login())
print(empleado4.login())
print(empleado5.login())
print(empleado6.login())
print(empleado7.login())
print(empleado8.login())
print(empleado9.login())
print(empleado10.login())

print(empleado1.marcarEntrada())
print(empleado2.marcarEntrada())
print(empleado3.marcarEntrada())
print(empleado4.marcarEntrada())
print(empleado5.marcarEntrada())
print(empleado6.marcarEntrada())
print(empleado7.marcarEntrada())
print(empleado8.marcarEntrada())
print(empleado9.marcarEntrada())
print(empleado10.marcarEntrada())

print(empleado1)
print(empleado2)
print(empleado3)
print(empleado4)
print(empleado5)
print(empleado6)
print(empleado7)
print(empleado8)
print(empleado9)
print(empleado10)

sala1 = Sala(1, "Sala IMAX", "Planta alta", "IMAX", 100, True)
sala2 = Sala(2, "Sala 3D", "Planta baja", "3D", 60, False)
sala3 = Sala(3, "Sala 4DX", "Nivel 1", "4DX", 80, True)
sala4 = Sala(4, "Sala VIP", "Nivel 2", "VIP", 40, True)
sala5 = Sala(5, "Sala 5", "Nivel 1", "Tradicional", 70, True)
sala6 = Sala(6, "Sala 6", "Nivel 2", "Tradicional", 65, True)
sala7 = Sala(7, "Sala 7", "Nivel 1", "Tradicional", 60, True)
sala8 = Sala(8, "Sala 8", "Nivel 2", "Tradicional", 55, True)
sala9 = Sala(9, "Sala 9", "Nivel 1", "Tradicional", 50, True)
sala10 = Sala(10, "Sala 10", "Nivel 2", "Tradicional", 45, True)

print(sala1)
print(sala2)
print(sala3)
print(sala4)
print(sala5)
print(sala6)
print(sala7)
print(sala8)
print(sala9)
print(sala10)

pelicula1 = Pelicula("Batman", 120, "B", "Acción")
pelicula2 = Pelicula("Toy Story", 95, "AA", "Animación")
pelicula3 = Pelicula("Avengers", 140, "B", "Acción")
pelicula4 = Pelicula("Frozen", 102, "AA", "Animación")
pelicula5 = Pelicula("Joker", 122, "C", "Drama")
pelicula6 = Pelicula("Titanic", 195, "B", "Romance")
pelicula7 = Pelicula("Matrix", 136, "B", "Ciencia Ficción")
pelicula8 = Pelicula("Coco", 105, "AA", "Animación")
pelicula9 = Pelicula("Gladiador", 155, "B", "Acción")
pelicula10 = Pelicula("Interestelar", 169, "B", "Ciencia Ficción")

print(pelicula1.obtenerSinopsis())
print(pelicula2.obtenerSinopsis())
print(pelicula3.obtenerSinopsis())
print(pelicula4.obtenerSinopsis())
print(pelicula5.obtenerSinopsis())
print(pelicula6.obtenerSinopsis())
print(pelicula7.obtenerSinopsis())
print(pelicula8.obtenerSinopsis())
print(pelicula9.obtenerSinopsis())
print(pelicula10.obtenerSinopsis())

funcion1 = Funcion(1, pelicula1, sala1, "20:00", 80)
funcion2 = Funcion(2, pelicula2, sala2, "18:00", 60)
funcion3 = Funcion(3, pelicula3, sala3, "19:00", 70)
funcion4 = Funcion(4, pelicula4, sala4, "17:00", 35)
funcion5 = Funcion(5, pelicula5, sala5, "21:30", 60)
funcion6 = Funcion(6, pelicula6, sala6, "16:00", 50)
funcion7 = Funcion(7, pelicula7, sala7, "20:30", 55)
funcion8 = Funcion(8, pelicula8, sala8, "15:00", 45)
funcion9 = Funcion(9, pelicula9, sala9, "22:00", 40)
funcion10 = Funcion(10, pelicula10, sala10, "18:30", 30)

print(funcion1.obtenerDetallesFuncion())
print(funcion2.obtenerDetallesFuncion())
print(funcion3.obtenerDetallesFuncion())
print(funcion4.obtenerDetallesFuncion())
print(funcion5.obtenerDetallesFuncion())
print(funcion6.obtenerDetallesFuncion())
print(funcion7.obtenerDetallesFuncion())
print(funcion8.obtenerDetallesFuncion())
print(funcion9.obtenerDetallesFuncion())
print(funcion10.obtenerDetallesFuncion())

promo1 = Promocion("DESC10", "Descuento 10%", 0.10, "31-12-2026")
promo2 = Promocion("DESC20", "Descuento 20%", 0.20, "31-12-2026")
promo3 = Promocion("DESC30", "Descuento 30%", 0.30, "31-12-2026")
promo4 = Promocion("DESC40", "Descuento 40%", 0.40, "31-12-2026")
promo5 = Promocion("DESC50", "Descuento 50%", 0.50, "31-12-2026")
promo6 = Promocion("DESC15", "Descuento 15%", 0.15, "31-12-2026")
promo7 = Promocion("DESC25", "Descuento 25%", 0.25, "31-12-2026")
promo8 = Promocion("DESC35", "Descuento 35%", 0.35, "31-12-2026")
promo9 = Promocion("DESC45", "Descuento 45%", 0.45, "31-12-2026")
promo10 = Promocion("DESC05", "Descuento 5%", 0.05, "31-12-2026")

print(promo1)
print(promo2)
print(promo3)
print(promo4)
print(promo5)
print(promo6)
print(promo7)
print(promo8)
print(promo9)
print(promo10)

reserva1 = Reserva(usuario1, funcion1, ["A1", "A2"])
reserva2 = Reserva(usuario2, funcion2, ["B1"])
reserva3 = Reserva(usuario3, funcion3, ["C1"])
reserva4 = Reserva(usuario4, funcion4, ["D1"])
reserva5 = Reserva(usuario5, funcion5, ["E1"])
reserva6 = Reserva(usuario6, funcion6, ["F1"])
reserva7 = Reserva(usuario7, funcion7, ["G1"])
reserva8 = Reserva(usuario8, funcion8, ["H1"])
reserva9 = Reserva(usuario9, funcion9, ["I1"])
reserva10 = Reserva(usuario10, funcion10, ["J1"])

usuario1.crearReserva(reserva1)
usuario2.crearReserva(reserva2)
usuario3.crearReserva(reserva3)
usuario4.crearReserva(reserva4)
usuario5.crearReserva(reserva5)
usuario6.crearReserva(reserva6)
usuario7.crearReserva(reserva7)
usuario8.crearReserva(reserva8)
usuario9.crearReserva(reserva9)
usuario10.crearReserva(reserva10)

print(reserva1)
print(reserva2)
print(reserva3)
print(reserva4)
print(reserva5)
print(reserva6)
print(reserva7)
print(reserva8)
print(reserva9)
print(reserva10)

print("\nTotal personas creadas:", Persona.total_personas)
print("Total reservas creadas:", Reserva.total_reservas)
